name: ML Pipeline

on:
  push:

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: pip install mlflow scikit-learn

      - name: Train model
        run: python train.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: model_info
          path: |
            model_info.txt
            accuracy.txt
            mlruns

  deploy:
    runs-on: ubuntu-latest
    needs: validate

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: pip install mlflow

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: model_info
          path: .

      # nested mlruns issue
      - name: Fix mlruns path
        run: |
          if [ -d "mlruns/mlruns" ]; then
            mv mlruns/mlruns/* mlruns/
            rm -r mlruns/mlruns
          fi

      # Debug
      - name: List files
        run: ls -R

      - name: Check accuracy
        run: python check_threshold.py

      - name: Mock Docker Build
        run: |
          echo "Building Docker image for Run ID: $(cat model_info.txt)"
